name: shellcheck and report

on:
  workflow_call:
    inputs:
      filename:
        # default filename is main.sh
        required: false
        type: string

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install shellcheck
        run: sudo apt install shellcheck

      - name: Set target file name
        id: target-file-name
        run: |
          # if input filename exists, return it.
          if [ -e {{ inputs.filename }} ]; then
            echo '::set-output name=FILE_NAME::{{ inputs.filename }}'
          # if input filename doesn't exist, return default value (=main.sh).
          else
            echo '::set-output name=FILE_NAME::main.sh'
          fi
      - name: Run shellcheck
        id: shell-check
        run: |
          set +e
          shellcheck ${{ steps.target-file-name.outputs.FILE_NAME }} &> result.txt
          echo "::set-output name=RESULT::$?"
          set -e

      - name: Report the results with no problem
        uses: actions/github-script@v5
        # pull-request AND NO problem with the target script file
        if: ${{ (github.event_name == 'pull_request') && (steps.shell-check.outputs.RESULT == 0) }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### CI/CD Results
            Hello, I'm kokoichi 👋

            No problem found in your target script file.`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Report the results with problem
        uses: actions/github-script@v5
        # pull-request AND problem found in the target script file
        if: ${{ (github.event_name == 'pull_request') && (steps.shell-check.outputs.RESULT > 0) }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### CI/CD Results
            Hello, I'm kokoichi 👋

            Problem found in your target script file.
            Please check your file.`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      # Save results to the artifacts if error found
      - name: Upload results when error found
        if: ${{ steps.shell-check.outputs.RESULT > 0 }}
        uses: actions/upload-artifact@v2
        with:
          name: license
          path: ./result.txt
          if-no-files-found: error
          retention-days: 3
      - name: Make the test fail when problem found
        if: ${{ steps.shell-check.outputs.RESULT > 0 }}
        run: exit 1
