name: shellcheck

on:
  workflow_call:
    inputs:
      filename:
        # default filename is main.sh
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install shellcheck
        run: sudo apt install shellcheck

      - name: Set target file name
        id: target-file-name
        run: |
          # if input filename exists, return it.
          if [ -e {{ inputs.filename }} ]; then
            echo '::set-output name=FILE_NAME::{{ inputs.filename }}'
          # if input filename doesn't exist, return default value (=main.sh).
          else
            echo '::set-output name=FILE_NAME::main.sh'
          fi
      - name: Run shellcheck
        id: shell-check
        run: |
          set +e
          shellcheck ${{ steps.target-file-name.outputs.FILE_NAME }}
          echo "::set-output name=RESULT::$?"
          set -e

      - name: Report the results
        uses: actions/github-script@v5
        # pull-request AND NO problem with the target script file
        if: ${{ (github.event_name == 'pull_request') && (steps.shell-check.outputs.RESULT == 0) }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### CI/CD Results
            Hello, I'm kokoichi 👋

            No problem found in your target script file.
      - name: Report the results
        uses: actions/github-script@v5
        # pull-request AND problem found in the target script file
        if: ${{ (github.event_name == 'pull_request') && (steps.shell-check.outputs.RESULT > 0) }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### CI/CD Results
            Hello, I'm kokoichi 👋
            ${{ steps.shell-check.outputs.RESULT }}

            Problem found in your target script file.
            Please check your file.
      - name: Make the test fail when problem found
        if: ${{ steps.shell-check.outputs.RESULT > 0 }}
        run: exit 1
