name: test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Run test
        id: shell-check
        run: |
          bash test.sh
